### GET MED
GET http://localhost:1010/doctor



### POST MED
POST http://localhost:1010/doctor/search
Accept: application/json
Content-Type: application/json

{
	"nome": "Fernando Furtado",
	"email": "fernando.furtado@gmail.com",
	"crm": "oftalmologista",
	"endereco": {
		"logradouro": "Rua a",
		"bairro": "Setor Cristina II Expansão",
		"cep": "75389328",
		"cidade": "Trindade",
		"uf": "GO",
		"numero": "4",
		"complemento": "casa"
	}
}