### GET MED NORMAL
GET http://localhost:1010/doctor

### GET MED PAGEABLE
GET http://localhost:1010/doctor?size=1&page=1

### GET MED PAGEABLE SORT DECRESCENT
GET http://localhost:1010/doctor?sort=nome,desc



### POST MED
POST http://localhost:1010/doctor/search
Accept: application/json
Content-Type: application/json

{
	"nome": "Fernando Furtado",
	"email": "fernando.furtado@gmail.com",
	"crm": "457895",
    "especialidade": "GINECOLOGIA",
	"endereco": {
		"logradouro": "Rua a",
		"bairro": "Setor Cristina II Expansão",
		"cep": "75389328",
		"cidade": "Trindade",
		"uf": "GO",
		"numero": "4",
		"complemento": "casa"
	}
}


### POST MED2
POST http://localhost:1010/doctor/search
Accept: application/json
Content-Type: application/json

{
  "nome": "Bruna Maria",
  "email": "bruna.maria@gmail.com",
  "crm": "123654",
  "telefone": "(62) 9 9563-1247",
  "especialidade": "CARDIOLOGIA",
  "endereco": {
    "logradouro": "Rua a",
    "bairro": "Setor Cristina II Expansão",
    "cep": "75389328",
    "cidade": "Trindade",
    "uf": "GO",
    "numero": "4",
    "complemento": "casa"
  }
}
